SCHEMA_VERSION = 2

TABLES = {
    "schema_version": {
        "id": "int PRIMARY KEY",
        "version": "int NOT NULL",
        "updated_at": "timestamptz NOT NULL",
    },
    "settings": {
        "key": "text PRIMARY KEY",
        "value_encrypted": "text NOT NULL",
        "updated_at": "timestamptz NOT NULL",
    },
    "logs": {
        "id": "bigserial PRIMARY KEY",
        "level": "text NOT NULL",
        "message": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "jobs": {
        "id": "bigserial PRIMARY KEY",
        "type": "text NOT NULL",
        "status": "text NOT NULL",
        "payload": "jsonb NOT NULL",
        "lease_until": "timestamptz",
        "attempts": "int NOT NULL DEFAULT 0",
        "last_error": "text",
        "created_at": "timestamptz NOT NULL",
        "updated_at": "timestamptz NOT NULL",
    },
    "targets": {
        "id": "bigserial PRIMARY KEY",
        "url": "text NOT NULL",
        "domain": "text NOT NULL",
        "ip": "text",
        "status": "text NOT NULL",
        "reason": "text",
        "risk_score": "int NOT NULL DEFAULT 0",
        "redirect_chain": "text",
        "dom_hash": "text",
        "headers_hash": "text",
        "headers_text": "text",
        "html_excerpt": "text",
        "html_path": "text",
        "favicon_hash": "text",
        "jarm": "text",
        "screenshot_path": "text",
        "screenshot_ahash": "text",
        "screenshot_phash": "text",
        "screenshot_dhash": "text",
        "screenshot_status": "text",
        "screenshot_reason": "text",
        "created_at": "timestamptz NOT NULL",
        "updated_at": "timestamptz NOT NULL",
    },
    "assets": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "url": "text NOT NULL",
        "type": "text NOT NULL",
        "md5": "text",
        "sha256": "text",
        "phash": "text",
        "ahash": "text",
        "status": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "indicators": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "kind": "text NOT NULL",
        "value": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "signatures": {
        "id": "bigserial PRIMARY KEY",
        "name": "text NOT NULL",
        "pattern": "text NOT NULL",
        "target_field": "text NOT NULL",
        "enabled": "boolean NOT NULL DEFAULT true",
        "created_at": "timestamptz NOT NULL",
    },
    "signature_matches": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "signature_id": "bigint NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "hunts": {
        "id": "bigserial PRIMARY KEY",
        "name": "text NOT NULL",
        "rule_type": "text NOT NULL",
        "rule": "text NOT NULL",
        "ttl_seconds": "int NOT NULL",
        "delay_seconds": "int NOT NULL",
        "budget": "int NOT NULL",
        "enabled": "boolean NOT NULL DEFAULT true",
        "last_run_at": "timestamptz",
        "created_at": "timestamptz NOT NULL",
    },
    "alerts": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "kind": "text NOT NULL",
        "message": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "campaigns": {
        "id": "bigserial PRIMARY KEY",
        "key": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "campaign_members": {
        "id": "bigserial PRIMARY KEY",
        "campaign_id": "bigint NOT NULL",
        "target_id": "bigint NOT NULL",
    },
    "graph_nodes": {
        "id": "bigserial PRIMARY KEY",
        "kind": "text NOT NULL",
        "value": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "graph_edges": {
        "id": "bigserial PRIMARY KEY",
        "from_node": "bigint NOT NULL",
        "to_node": "bigint NOT NULL",
        "kind": "text NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "iocs": {
        "id": "bigserial PRIMARY KEY",
        "kind": "text NOT NULL",
        "value": "text NOT NULL",
        "target_id": "bigint",
        "url": "text",
        "domain": "text",
        "source": "text",
        "note": "text",
        "created_at": "timestamptz NOT NULL",
    },
    "yara_rules": {
        "id": "bigserial PRIMARY KEY",
        "name": "text NOT NULL",
        "rule_text": "text NOT NULL",
        "target_field": "text NOT NULL",
        "enabled": "boolean NOT NULL DEFAULT true",
        "created_at": "timestamptz NOT NULL",
    },
    "yara_matches": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "asset_id": "bigint",
        "rule_id": "bigint NOT NULL",
        "created_at": "timestamptz NOT NULL",
    },
    "urlscan_local": {
        "id": "bigserial PRIMARY KEY",
        "target_id": "bigint NOT NULL",
        "url": "text NOT NULL",
        "domain": "text NOT NULL",
        "ip": "text",
        "title": "text",
        "status": "text NOT NULL",
        "content_type": "text",
        "redirect_chain": "text",
        "dom_hash": "text",
        "headers_hash": "text",
        "favicon_hash": "text",
        "jarm": "text",
        "created_at": "timestamptz NOT NULL",
    },
}

INDEXES = {
    "jobs": ["status", "lease_until"],
    "targets": ["domain", "status"],
    "signatures": ["enabled"],
    "graph_nodes": ["kind", "value"],
    "urlscan_local": ["domain", "dom_hash", "headers_hash", "ip", "jarm", "favicon_hash"],
}

VIEWS = {
    "assets_view": "SELECT * FROM assets",
}
